// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/d-agents.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadStatus_Status int32

const (
	WorkloadStatus_UNKNOWN   WorkloadStatus_Status = 0
	WorkloadStatus_PENDING   WorkloadStatus_Status = 1
	WorkloadStatus_RUNNING   WorkloadStatus_Status = 2
	WorkloadStatus_COMPLETED WorkloadStatus_Status = 3
	WorkloadStatus_FAILED    WorkloadStatus_Status = 4
)

// Enum value maps for WorkloadStatus_Status.
var (
	WorkloadStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "COMPLETED",
		4: "FAILED",
	}
	WorkloadStatus_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"PENDING":   1,
		"RUNNING":   2,
		"COMPLETED": 3,
		"FAILED":    4,
	}
)

func (x WorkloadStatus_Status) Enum() *WorkloadStatus_Status {
	p := new(WorkloadStatus_Status)
	*p = x
	return p
}

func (x WorkloadStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_d_agents_proto_enumTypes[0].Descriptor()
}

func (WorkloadStatus_Status) Type() protoreflect.EnumType {
	return &file_proto_d_agents_proto_enumTypes[0]
}

func (x WorkloadStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadStatus_Status.Descriptor instead.
func (WorkloadStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_d_agents_proto_rawDescGZIP(), []int{1, 0}
}

type Workload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Models        []string               `protobuf:"bytes,3,rep,name=models,proto3" json:"models,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentId       string                 `protobuf:"bytes,7,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        WorkloadStatus_Status  `protobuf:"varint,8,opt,name=status,proto3,enum=proto.WorkloadStatus_Status" json:"status,omitempty"`
	AgentType     string                 `protobuf:"bytes,9,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_proto_d_agents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_d_agents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_proto_d_agents_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *Workload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Workload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Workload) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Workload) GetStatus() WorkloadStatus_Status {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_UNKNOWN
}

func (x *Workload) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

type WorkloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Status        WorkloadStatus_Status  `protobuf:"varint,2,opt,name=status,proto3,enum=proto.WorkloadStatus_Status" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_proto_d_agents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_d_agents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_proto_d_agents_proto_rawDescGZIP(), []int{1}
}

func (x *WorkloadStatus) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadStatus) GetStatus() WorkloadStatus_Status {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_UNKNOWN
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_d_agents_proto protoreflect.FileDescriptor

const file_proto_d_agents_proto_rawDesc = "" +
	"\n" +
	"\x14proto/d-agents.proto\x12\x05proto\"\x90\x02\n" +
	"\bWorkload\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06models\x18\x03 \x03(\tR\x06models\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bagent_id\x18\a \x01(\tR\aagentId\x124\n" +
	"\x06status\x18\b \x01(\x0e2\x1c.proto.WorkloadStatus.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"agent_type\x18\t \x01(\tR\tagentType\"\xcd\x01\n" +
	"\x0eWorkloadStatus\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.proto.WorkloadStatus.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"J\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\r\n" +
	"\tCOMPLETED\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x042C\n" +
	"\x06Worker\x129\n" +
	"\x0fExecuteWorkload\x12\x0f.proto.Workload\x1a\x15.proto.WorkloadStatusB#Z!github.com/nieveai/d-agents/protob\x06proto3"

var (
	file_proto_d_agents_proto_rawDescOnce sync.Once
	file_proto_d_agents_proto_rawDescData []byte
)

func file_proto_d_agents_proto_rawDescGZIP() []byte {
	file_proto_d_agents_proto_rawDescOnce.Do(func() {
		file_proto_d_agents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_d_agents_proto_rawDesc), len(file_proto_d_agents_proto_rawDesc)))
	})
	return file_proto_d_agents_proto_rawDescData
}

var file_proto_d_agents_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_d_agents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_d_agents_proto_goTypes = []any{
	(WorkloadStatus_Status)(0), // 0: proto.WorkloadStatus.Status
	(*Workload)(nil),           // 1: proto.Workload
	(*WorkloadStatus)(nil),     // 2: proto.WorkloadStatus
}
var file_proto_d_agents_proto_depIdxs = []int32{
	0, // 0: proto.Workload.status:type_name -> proto.WorkloadStatus.Status
	0, // 1: proto.WorkloadStatus.status:type_name -> proto.WorkloadStatus.Status
	1, // 2: proto.Worker.ExecuteWorkload:input_type -> proto.Workload
	2, // 3: proto.Worker.ExecuteWorkload:output_type -> proto.WorkloadStatus
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_d_agents_proto_init() }
func file_proto_d_agents_proto_init() {
	if File_proto_d_agents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_d_agents_proto_rawDesc), len(file_proto_d_agents_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_d_agents_proto_goTypes,
		DependencyIndexes: file_proto_d_agents_proto_depIdxs,
		EnumInfos:         file_proto_d_agents_proto_enumTypes,
		MessageInfos:      file_proto_d_agents_proto_msgTypes,
	}.Build()
	File_proto_d_agents_proto = out.File
	file_proto_d_agents_proto_goTypes = nil
	file_proto_d_agents_proto_depIdxs = nil
}
